### ISSUE TITLE
Language-neutral language selection menu

### ISSUE THREAD

**Issue by waldyrious** [katherinepeterson/readme.so#125]
_(Originally posted [here](https://github.com/katherinepeterson/readme.so/issues/124#issuecomment-829968648).)_

This is related to what was described in #93 (/cc @hey-fk): when someone is seeing the site in a language that they don't speak, they will want to change to another language that they do understand, but the fact that the label of the "language" menu is localized will make this hard. For example, if the page is being shown in Turkish, I'd have no idea that "Dil" means "language" in Turkish, so I wouldn't be able to find the language-switching menu.

IMO it would be more appropriate to use a language-indepenent symbol. For example:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Translation_-_Noun_project_987.svg/100px-Translation_-_Noun_project_987.svg.png) ([source](https://commons.wikimedia.org/wiki/File:Translation_-_Noun_project_987.svg))

or

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Noun_Project_translation_icon_24074_cc.svg/100px-Noun_Project_translation_icon_24074_cc.svg.png) ([source](https://commons.wikimedia.org/wiki/File:Noun_Project_translation_icon_24074_cc.svg))

**Comment by Gilvan-Araujo** [comment]
I would like to claim that issue, and get it assigned to me. Thanks.
