### ISSUE TITLE
Prevent losing README draft accidently

### ISSUE THREAD

**Issue by cowchimp** [katherinepeterson/readme.so#139]
Hi.
Thanks for this handy tool.
I just used to put together a README and spent about half an hour composing it. I then accidentally clicked one of the links in the preview pane and the page navigated away to that page all the content I wrote was lost 😅

Would be nice IMO if the page prevented accidents like these by showing a pop-up asking the user if it was truly their intent to navigate away, or instead of perhaps use `localStorage` to save their progress if they do navigate.

Thanks.

**Comment by saurabhchaturvedy** [comment]
Hi @cowchimp , there's already an issue #81 opened by me, on which i am working.

**Comment by cowchimp** [comment]
Sorry @saurabhchaturvedy I tried to look for relevant issues before creating this one but I missed it. Closing this issue.
