### ISSUE TITLE
Translation Issue [German]

### ISSUE THREAD

**Issue by Intevel** [katherinepeterson/readme.so#146]
The word "zurücksetzen" would mean to reset in German, but it says "Reset", when I set the language to German

**Comment by MicahBCode** [comment]
The word "reset" is correct according to [Duden](https://www.duden.de/rechtschreibung/Reset). The word "Reset" belongs to the anglicisms. It's aswell in the wikipedia list for anglicisms see [here](https://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Anglizismen).

In my opinion there should be any changes made.
