### ISSUE TITLE
Mac emoji shortcut support

### ISSUE THREAD

**Issue by katherinepeterson** [katherinepeterson/readme.so#2]
Feedback from Twitter: 

the text areas won't accept the (crtl + cmd + space) mac shortcut for bringing the emojis menu

**Comment by RoccoSangellino** [comment]
This seems to work for me on a Macbook Pro.

![image](https://user-images.githubusercontent.com/60282108/114292654-2e026400-9a4d-11eb-9908-f7bbf4114e8b.png)

**Comment by katherinepeterson** [comment]
@RoccoSangellino oh weird you're right, it works for me too. Didn't test it, just got that feedback from someone on Twitter. I'll close this issue.
