### ISSUE TITLE
Add light/dark theme toggle to editor

### ISSUE THREAD

**Issue by katherinepeterson** [katherinepeterson/readme.so#29]
The Editor component takes a string for a theme. It currently is set to "vs-dark"

- [ ] add a dark mode toggle button that toggles the editor theme between "vs-dark" and "vs"

**Comment by saurabhchaturvedy** [comment]
Hi @katherinepeterson , i came across readme.so recently , and would like to give it a shot by contributing to this issue . I am a java backend developer , but do understand frontend development as required during a task . Let me know if i can take time and pick up this feature ?

**Comment by katherinepeterson** [comment]
> Hi @katherinepeterson , i came across readme.so recently and find it interesting, and would like to give it a shot by contributing to this issue . I am a java backend developer , but do understand frontend development as required during a task . Let me know if i can take time and pick up this feature ?

Yes, definitely please do! I am assigning the issue to you

**Comment by saurabhchaturvedy** [comment]
Thanks @katherinepeterson , will start this now and will update you .
