### ISSUE TITLE
Adding support for i18n

### ISSUE THREAD

**Issue by rohitjmathew** [katherinepeterson/readme.so#30]
I saw that we should be able to add support to i18n with the following [dependency](https://github.com/isaachinman/next-i18next). Thoughts on adding this to the site?

**Comment by katherinepeterson** [comment]
@rohitjmathew That seems great!

**Comment by rohitjmathew** [comment]
Great @katherinepeterson. I'll start work on this. FYI, I work mostly with a backend codebase (java and some node services) but let me give this a shot. Hope you could code review this and give me tips if I mess up?

**Comment by katherinepeterson** [comment]
Yeah, definitely!

**Comment by pedrozebra** [comment]
Hi, i could add support to italian locale when i18n integration would be released.
Thank you
