### ISSUE TITLE
Design bug: The body is bigger than the actual screen

### ISSUE THREAD

**Issue by szhabolcs** [katherinepeterson/readme.so#31]
This might just be a personal preference, but the whole body overflows and a scrolling bar is seen:
![image](https://user-images.githubusercontent.com/54114237/114355453-28556d00-9b78-11eb-8541-b72cb3a36fef.png)

And since the left side menu is already a scrolling one, I don't think the whole body should scroll too. 
I see the three elements have `max-h-screen` to be as tall as the screen, but since there is a header on the top, and some text as well, the overflowing happens.

**Comment by katherinepeterson** [comment]
@szhabolcs thanks! I agree with you, the body shouldn't scroll

**Comment by jai-dewani** [comment]
I was able to get everything to one page but I had hardcode their height to `80vh` or `85vh` if we really wanna stretch them to the end of the screen. I suppose there should be a better way to do this since I am no good at CSS styling.   

A ScreenShot of how it looked 

![image](https://user-images.githubusercontent.com/33520257/114449386-4e1f5800-9bf2-11eb-8d61-4207ecf908aa.png)

**Comment by szhabolcs** [comment]
Making a new Tailwind class, or overwriting the existing `max-h-screen` class (I would recommend the first one) fixes the issue:
```
.max-h-screen {
    max-height: calc(100vh - 170px);
}
```
![image](https://user-images.githubusercontent.com/54114237/114452662-633fbb00-9be1-11eb-8244-70347b6bf501.png)
Even on smaller screens:
![image](https://user-images.githubusercontent.com/54114237/114452735-7783b800-9be1-11eb-80ef-21e269e2c11d.png)

Ps. I'd ask for someone else to make a commit. I don't have time to set up the project atm 😅. 
Also the center editor part needs to have this new class also.

**Comment by jai-dewani** [comment]
Thanks @szhabolcs for this neat solution, if no one else wants to do this then I will make a PR with these changes ✌️

**Comment by tomhicks** [comment]
You're better off using flexbox or grid here to make things expand. That means that if your 170px changes to something else, later on, you don't have to go changing random other bits of CSS to prevent everything breaking.

**Comment by szhabolcs** [comment]
@tomhicks yeah, I do agree, the layout itself would need some sort of rework. 
I read that some people are working on making the website responsive, and I assume they take a mobile first approach since we're using Tailwind. And hence the layout should somewhat change in the future, and with it this bug should get a proper fix. But as of now, I think this temporary solution is decent.
