### ISSUE TITLE
Disable text selection highlighting on section buttons

### ISSUE THREAD

**Issue by katherinepeterson** [katherinepeterson/readme.so#33]
![Screen Shot 2021-04-12 at 10 24 06 AM](https://user-images.githubusercontent.com/49968061/114435726-58514000-9b79-11eb-9fea-23b49207153f.png)

Sometimes I accidentally highlight the text of the section buttons when I'm trying to drag and drop

**Comment by jaymanale** [comment]
Hi, @katherinepeterson 
I would like to work on this issue.
