### ISSUE TITLE
Removing a section from my readme banishes it forever

### ISSUE THREAD

**Issue by tomhicks** [katherinepeterson/readme.so#37]
I should be able to re-add a section that I've removed. At the moment, if I add a section, then remove it, there's no way to re-add it.

For instance, I want to see what is in each section. I click on each one in turn, which adds it to the list. I don't want to add it right now, so I delete it. Now I can't find it again.

**Comment by katherinepeterson** [comment]
@tomhicks it shouldn't disappear forever, right now if you delete a section it just gets added to the bottom of the sections list. 

It's probably confusing that it doesn't go back to the same place in the list where it started, right?

**Comment by jamesncox** [comment]
I think I've got a relatively easy solution for now: alphabetize the sections so when you map through them, they return to the same spot on the list. This might be less jarring for the user, to have visual confirmation that their deleted section returns to the same sport in the list.
