### ISSUE TITLE
"Clear All" kind of functionality to clean up the added readme sections to start fresh 

### ISSUE THREAD

**Issue by saurabhchaturvedy** [katherinepeterson/readme.so#39]
Currently , when a user wants to reset its readme file's content (i.e start from scratch with just the 'title and description' template) , he/she has to refresh the entire page in chrome/any browser . Currently we can delete individual sections by clicking on delete icon one by one , but can't delete all at one . So , should we support a "clear all" to clean up all sections at once or let us just browser refresh do it for now ?  Also , is the browser refresh supposed to clean-up all the used sections while a user is creating a readme , and in middle of it the progress is lost if he just refreshes the browser (if he didn't backed up the document by downloading in-between) ?  While working with swagger editor online for designing APIs i have experienced , it saves the state for the current session of user from local storage with any custom changes , even if he refreshes browser as here : https://editor.swagger.io/ .

![image](https://user-images.githubusercontent.com/56601821/114543254-954f2c80-9c76-11eb-83da-dc43a6b56ed9.png)

**Comment by katherinepeterson** [comment]
Yes right now nothing is persisted, so refreshing the browser resets everything.

I think the best path forward here would be to first implement saving the state to local storage, then implement a clear all button
