### ISSUE TITLE
UI  heading : suggested alignment for consistency.

### ISSUE THREAD

**Issue by saurabhchaturvedy** [katherinepeterson/readme.so#51]
@katherinepeterson after having look at raw-markdown-preview-feature added by @jmolina518 , i just had a thought for a small UI change , if we could align the headings to match with the smaller font & liked the color scheme used by @jmolina518 , it's looking sleek & smart than bigger headings as of now .

**Current editor UI :**
![image](https://user-images.githubusercontent.com/56601821/114686073-11f21180-9d30-11eb-9c57-c4880afef011.png)

**Suggested Change**

![image](https://user-images.githubusercontent.com/56601821/114686256-3d74fc00-9d30-11eb-9800-f0abfce10cfb.png)

**Comment by katherinepeterson** [comment]
Sure, that looks good to me!

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson I'll take it up
