### ISSUE TITLE
Add "e" button shortcut to focus editor

### ISSUE THREAD

**Issue by katherinepeterson** [katherinepeterson/readme.so#57]

**Comment by MicahBCode** [comment]
Hey Katherine,

I would like to take that one.

What was your idea? Just having an "e"-shortcut if the editor is not focused or from where did you mean that one should be accessible?

Best regards :)

**Comment by katherinepeterson** [comment]
Yeah, I think it would work from anywhere outside of the editor.

**Comment by MicahBCode** [comment]
Alright. I'll take that. 👍
