### ISSUE TITLE
Add custom section feature

### ISSUE THREAD

**Issue by octokatherine** [katherinepeterson/readme.so#6]
Allow user to add custom sections
- They should be able to name the section and edit the contents

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson , i would like to take this up . How we want the user flow to be ? My idea would be 

(i.) Provide a '+' icon next to the section heading , on which user can click to add a new section .
(ii.) On clicking the '+', we display a pop-up modal to the user , asking him to fill the name , content , and a button labelled as 'ADD' to let it add to the existing list of section slugs available for selection .

**Comment by katherinepeterson** [comment]
Hey @saurabhchaturvedy, I think this issue might already be in progress by @jamesncox

**Comment by saurabhchaturvedy** [comment]
cool @katherinepeterson , will find something else to contribute !

**Comment by ananyalohani** [comment]
Hi @octokatherine! Is this issue still in progress? If not, can I take it up?

**Comment by octokatherine** [comment]
@ananyalohani please do, thanks!
