### ISSUE TITLE
Suggested change : "Authors" and "Acknowledgement" should be separate sections

### ISSUE THREAD

**Issue by saurabhchaturvedy** [katherinepeterson/readme.so#66]
@katherinepeterson , i think its better to keep authors and acknowledgement sections as separate , as they kinda serve a bit different purpose , also one unassumed benefit would be that the section name also would not be unnecessary too long which might also avoid bloating UI alignment in future .

**My understanding on purpose of sections** :
Authors -- can be used mention the key authors of the codebase/project
Acknowledgements - also mean crediting other libs , projects , of which help/inspiration was taken to build a project . One such example here :  https://github.com/othneildrew/Best-README-Template

**Comment by katherinepeterson** [comment]
Yep, this change sounds good to me!
