### ISSUE TITLE
Add italian language support i18n

### ISSUE THREAD

**Issue by pedrozebra** [katherinepeterson/readme.so#71]
Hi @katherinepeterson , i can add italian language support.

**Comment by rohitjmathew** [comment]
@pedrozebra was just going to comment that you can add Italian support now. Great to see you created the issue already 👍

**Comment by pedrozebra** [comment]
@rohitjmathew @katherinepeterson  which version of node is recommended for install dependencies?

**Comment by rohitjmathew** [comment]
@katherinepeterson you can close this issue as the PR is already merged
