### ISSUE TITLE
The site does not fully fit into the window

### ISSUE THREAD

**Issue by omerayyildiz** [katherinepeterson/readme.so#91]
![image](https://user-images.githubusercontent.com/34156233/115994717-cfa6bb00-a5e0-11eb-9017-26060901b704.png)

**Comment by MicahBCode** [comment]
Well... @katherinepeterson Do you remember the specific reason for adding the App min width in the follwing commit in the pages/editor.js file?
[https://github.com/katherinepeterson/readme.so/commit/909bea962d6f55449d58a14cea0598d829c59c4c#diff-f1c67288e5f8f7ee1c99bb782bc2562cfdee1f305aad2ed5a6de6ef2f26934a7](url)
