### ISSUE TITLE
Language definitions localization advice

### ISSUE THREAD

**Issue by hey-fk** [katherinepeterson/readme.so#93]
Each language should be written in their original/ local language in every language pages of the website. If I am in the website which is Spanish as a Turkish person, I should see "Türkçe" word as an option in the language dropdown not "Turco" which is called by Spanish people. Because I may not be able to know the definition of "Türkçe" in Spanish. So here is my advices below:
Every languages should be the same in all language pages.
English,
Français,
Español,
Italiano,
Türkçe

If you agree with me I can fix it.

**Comment by katherinepeterson** [comment]
I agree with this! Thanks!
