### ISSUE TITLE
Turkish Typo Fixes

### ISSUE THREAD

**Issue by hey-fk** [katherinepeterson/readme.so#99]
Turkish language ISO code is "TR" not "TUR". Also there are some typo mistakes in Turkish translation.

**Comment by izzetkalic** [comment]
Were you able to run with "tr"? In someway it always route to /tr even if you select "en". This is why I used "tur".

**Comment by hey-fk** [comment]
It automatically detects and redirects from the browser language. To turn it off, localeDetection must be set to false in the i18n setting. This situation works in the other languages as well. As another option, the English language address can be changed to /en in dropdown.

**Comment by izzetkalic** [comment]
O see, thanks for explanation and typo fix 🙏
